### ISSUE TITLE
Navbars

### ISSUE THREAD

**Issue by AlexanderBemol** [davitron2/pw20201mvc#2]
Crear los 3 navbars para los 3 tipos de usuario (alumno, profesor y docente), incluyendo solo los modulos a los que puede acceder cada uno de ellos
**Administrativos**
- Alumnos
- Personal
- Aulas
- Materias
- Grupos

**Docentes**
- Grupos
- Horario

**Alumnos**
- Horario
- Calificaciones Parciales
- Boletas
- Inscripciones

**Comment by AlexisOzaetaM** [comment]
En ese orden las opciones?

**Comment by AlexanderBemol** [comment]
no necesariamente, como prefieras

**Comment by AlexanderBemol** [comment]
También los docentes tendrían acceso a calificaciones parciales y calificacion final (boleta) pero no se su quede mejor en una  opción allí, o luego de abrir la opción de grupos, lo dejo a consideración

**Comment by AlexisOzaetaM** [comment]
Okay, les agrego también las opciones de **cambio de nip** y **cerrar sesión**? O solo esa última?

**Comment by AlexisOzaetaM** [comment]
> También los docentes tendrían acceso a calificaciones parciales y calificacion final (boleta) pero no se su quede mejor en una  opción allí, o luego de abrir la opción de grupos, lo dejo a consideración

Como opciones en el submenú creo estarán mejor

**Comment by AlexanderBemol** [comment]
> 
> 
> Okay, les agrego también las opciones de **cambio de nip** y **cerrar sesión**? O solo esa última?

sí, una parte como de sesión, y tenga ambas opciones, en los otros usuarios sería cambio de contraseña
